### ISSUE TITLE
Request for project files

### ISSUE THREAD

**Issue by murtaza98** [Jacob12138xieyuan/real-time-3d-pose-estimation-with-Unity3D-public#2]
Hello,
This is Murtaza, and I am working on a similar project and I would like to refer through ur files related to this project for reference, so I was hoping if u could share them with me, it would be really really helpful. U could mail me the files at [m.patrawala@somaiya.edu ](url).

Thanks in advance

**Comment by Jacob12138xieyuan** [comment]
in another repo, thanks

**Comment by g5059** [comment]
@Jacob12138xieyuan  could you provide a link to the repo.  I am not able to locate it.

**Comment by Jacob12138xieyuan** [comment]
https://github.com/Jacob12138xieyuan/real-time-3d-pose-estimation-with-Unity3D/settings
